config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :two_wheelers, controller: 'vehicles', type: 'TwoWheeler' 
  resources :four_wheelers, controller: 'vehicles', type: 'FourWheeler' 
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
	validates :name, presence: true, uniqueness: true

	has_many :company_vehicles
	has_many :vehicles, through: :company_vehicles

	has_many :two_wheelers, -> { where(type: 'TwoWheeler') }, through: :company_vehicles, source: :vehicle
	has_many :four_wheelers, -> { where(type: 'FourWheeler') }, through: :company_vehicles, source: :vehicle

	def method_missing(method_name,*args, &block)
		method_name.to_s+" does not defined"
	end

	def self.create_certificate_method(certification_name)
		define_method(certification_name) do |args|
			"Company #{name} is certified with #{certification_name}"
		end
	end
end

app/models/company_vehicle.rb
class CompanyVehicle < ApplicationRecord
  belongs_to :company
  belongs_to :vehicle
end

app/models/four_wheeler.rb
class FourWheeler < Vehicle
end

app/models/two_wheeler.rb
class TwoWheeler < Vehicle
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	COMMON_VEHICLES = %i[pulsar zen indica]
	validates :name, presence: true, uniqueness: true

	has_many :company_vehicles
	has_many :companies, through: :company_vehicles

	after_create :create_self_check_method

	COMMON_VEHICLES.each do |method_name|
	    define_method "#{method_name}?" do
	      name == method_name
	    end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, vehicle_ids: [])
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new(type: params[:type])
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
       params.fetch(:two_wheeler, params.fetch(:four_wheeler, {})).permit(:name, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>
  <p>
    <strong>Two Wheelers:</strong>
    <%= company.two_wheelers.collect(&:name).join(", ") %>
  </p>
  <p>
    <strong>Four Wheelers:</strong>
    <%= company.four_wheelers.collect(&:name).join(", ") %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <h4>Two Wheelers</h4>
    <%= form.collection_select(:vehicle_ids, TwoWheeler.all, :id, :name, {}, { multiple: true }) %>
  </div>
  <div>
    <h4>Four Wheelers</h4>
    <%= form.collection_select(:vehicle_ids, FourWheeler.all, :id, :name, {}, { multiple: true }) %>
  </div>

  <div style="margin-top:10px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
      <%= link_to "Show this company", company %>
    </p>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Back to companies", companies_path %>

  <%= button_to "Destroy this company", @company, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="margin: 50px 200px;">
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <p>
    <strong>Name:</strong>
    <%= vehicle.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= vehicle.type %>
  </p>

</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vehicles</h1>
<%= link_to "New Two Wheeler", new_vehicle_path(type: "TwoWheeler") %>
<%= link_to "New Four Wheeler", new_vehicle_path(type: "FourWheeler") %>
<div id="vehicles">
  <% @vehicles.each do |vehicle| %>
    <%= render "vehicles/vehicle", vehicle: vehicle %>
    <p>
      <%= link_to "Show this vehicle", vehicle_path(vehicle) %>
    </p>
    <hr>
  <% end %>
</div>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "vehicles/vehicle", vehicle: @vehicle %>

<div>
  <%= link_to "Edit this vehicle", edit_vehicle_path(@vehicle) %> |
  <%= link_to "Back to vehicles", vehicles_path %>

  <%= button_to "Destroy this vehicle", vehicle_path(@vehicle), method: :delete %>
</div>